[project]
name="mlit-geospatial-mcp"
version="0.0.1"
requires-python = ">=3.12"
dependencies = [
    "anyio",
    "mcp",
    "shapely",
    "pyproj",
    "requests",
    "asyncio",
    "structlog>=25.6.0",
    "opentelemetry-distro>=0.65b0",
    "opentelemetry-exporter-otlp-proto-http>=1.44.0",
    "opentelemetry-instrumentation-requests>=0.65b0",
]

[dependency-groups]
dev = [
  "pytest>=9.0.3",
]
